### ISSUE TITLE
Missing header

### ISSUE THREAD

**Issue by briandgregory** [ylmrx/maxisynthsvf#1]
>> Installing /workspace/drumlogue/maxisynthsvf/
Compiling header.c
Compiling _unit_base.c
Compiling unit.cc
In file included from unit.cc:13:0:
synth.h:18:24: fatal error: maximilian.h: No such file or directory
 #include "maximilian.h"

**Comment by ylmrx** [comment]
(Dupe solved issue on snh, closing)
